optimizer: Adam 
amsgrad: 1   #for adam optim



#model-related
model:
  nb_samp: 64600
  first_conv: 1024   # no. of filter coefficients 
  in_channels: 1
  layers: [3, 4, 6, 3] # no. of filters channel in residual blocks
  filts: 64
  blocks: [2, 4]
  nb_fc_node: 1024
  gru_node: 1024
  nb_gru_layer: 3
  num_classes: 2



  
  



